# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\edvs\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1084, 645)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(49, 49, 49);\n"
"}\n"
"QWidget{\n"
"    background-color: rgb(49, 49, 49);\n"
"}\n"
"QFrame{\n"
"    background-color: rgb(49, 49, 49);\n"
"}\n"
"\n"
"QStatusBar{\n"
"    color: rgba(255, 255, 255,0.5);\n"
"    \n"
"    font:7.5pt \"Arame Mono\";\n"
"    border-top: 1px solid rgba(20, 20, 20, 0.9);;\n"
"    background-color: rgb(35, 35, 35);\n"
"}\n"
"\n"
"QSizeGrip{\n"
"    border-top: 1px solid rgba(20, 20, 20, 0.9);;\n"
"    background-color: rgba(0, 0, 0, 0.0);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"    margin: 0 1;    \n"
"    image: url(:/src/icons/grip_icon.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arame Mono")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("font: 9pt \"Arame Mono\";")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fr_top_bar = QtWidgets.QFrame(self.centralwidget)
        self.fr_top_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.fr_top_bar.setStyleSheet("QPushButton{\n"
"border: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 0.3)\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(205, 205, 205, 0.3)\n"
"}")
        self.fr_top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_top_bar.setObjectName("fr_top_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fr_top_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_togle_menu = QtWidgets.QPushButton(self.fr_top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_togle_menu.sizePolicy().hasHeightForWidth())
        self.btn_togle_menu.setSizePolicy(sizePolicy)
        self.btn_togle_menu.setMinimumSize(QtCore.QSize(50, 35))
        self.btn_togle_menu.setMaximumSize(QtCore.QSize(45, 35))
        self.btn_togle_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_togle_menu.setStyleSheet("QPushButton{\n"
"    background-color: rgb(39, 39, 39);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(59, 59, 59);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(155, 155, 155, 0.2)\n"
"}")
        self.btn_togle_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/icons/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_togle_menu.setIcon(icon)
        self.btn_togle_menu.setIconSize(QtCore.QSize(29, 29))
        self.btn_togle_menu.setObjectName("btn_togle_menu")
        self.horizontalLayout.addWidget(self.btn_togle_menu)
        self.line_3 = QtWidgets.QFrame(self.fr_top_bar)
        self.line_3.setMinimumSize(QtCore.QSize(1, 0))
        self.line_3.setMaximumSize(QtCore.QSize(1, 45))
        self.line_3.setStyleSheet("background-color: rgba(0, 0, 0, 0.5);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.time_label = QtWidgets.QLabel(self.fr_top_bar)
        self.time_label.setMinimumSize(QtCore.QSize(149, 0))
        self.time_label.setStyleSheet("color: rgba(255, 255, 255, 0.2);\n"
"background-color: rgb(39, 39, 39);")
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.horizontalLayout.addWidget(self.time_label)
        self.line_hide_4 = QtWidgets.QFrame(self.fr_top_bar)
        self.line_hide_4.setMinimumSize(QtCore.QSize(1, 0))
        self.line_hide_4.setMaximumSize(QtCore.QSize(1, 45))
        self.line_hide_4.setStyleSheet("background-color: rgba(0, 0, 0, 0.5);")
        self.line_hide_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_hide_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_hide_4.setObjectName("line_hide_4")
        self.horizontalLayout.addWidget(self.line_hide_4)
        self.lb_countdown = QtWidgets.QLabel(self.fr_top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_countdown.sizePolicy().hasHeightForWidth())
        self.lb_countdown.setSizePolicy(sizePolicy)
        self.lb_countdown.setMinimumSize(QtCore.QSize(76, 35))
        self.lb_countdown.setMaximumSize(QtCore.QSize(79, 35))
        self.lb_countdown.setStyleSheet("QLabel{\n"
"color: rgba(255, 255, 255, 0.2);\n"
"background-color: rgb(39, 39, 39);\n"
"}\n"
"\n"
"QLabel:hover{\n"
"color: rgba(255, 255, 255, 0.2);\n"
"}")
        self.lb_countdown.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_countdown.setObjectName("lb_countdown")
        self.horizontalLayout.addWidget(self.lb_countdown)
        self.line_hide_2 = QtWidgets.QFrame(self.fr_top_bar)
        self.line_hide_2.setMinimumSize(QtCore.QSize(1, 0))
        self.line_hide_2.setMaximumSize(QtCore.QSize(1, 45))
        self.line_hide_2.setStyleSheet("background-color: rgba(0, 0, 0, 0.5);")
        self.line_hide_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_hide_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_hide_2.setObjectName("line_hide_2")
        self.horizontalLayout.addWidget(self.line_hide_2)
        self.lb_telemetry_info_1 = QtWidgets.QLabel(self.fr_top_bar)
        self.lb_telemetry_info_1.setMinimumSize(QtCore.QSize(76, 35))
        self.lb_telemetry_info_1.setMaximumSize(QtCore.QSize(79, 35))
        self.lb_telemetry_info_1.setStyleSheet("color: rgba(255, 255, 255, 0.2);\n"
"background-color: rgb(39, 39, 39);")
        self.lb_telemetry_info_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_telemetry_info_1.setObjectName("lb_telemetry_info_1")
        self.horizontalLayout.addWidget(self.lb_telemetry_info_1)
        self.line_hide_3 = QtWidgets.QFrame(self.fr_top_bar)
        self.line_hide_3.setMinimumSize(QtCore.QSize(1, 0))
        self.line_hide_3.setMaximumSize(QtCore.QSize(1, 45))
        self.line_hide_3.setStyleSheet("background-color: rgba(0, 0, 0, 0.5);")
        self.line_hide_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_hide_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_hide_3.setObjectName("line_hide_3")
        self.horizontalLayout.addWidget(self.line_hide_3)
        spacerItem = QtWidgets.QSpacerItem(797, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_minimize = QtWidgets.QPushButton(self.fr_top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setMinimumSize(QtCore.QSize(55, 35))
        self.btn_minimize.setMaximumSize(QtCore.QSize(55, 35))
        self.btn_minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_minimize.setStyleSheet("")
        self.btn_minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/src/icons/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon1)
        self.btn_minimize.setIconSize(QtCore.QSize(29, 29))
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout.addWidget(self.btn_minimize)
        self.btn_normalize = QtWidgets.QPushButton(self.fr_top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_normalize.sizePolicy().hasHeightForWidth())
        self.btn_normalize.setSizePolicy(sizePolicy)
        self.btn_normalize.setMinimumSize(QtCore.QSize(55, 35))
        self.btn_normalize.setMaximumSize(QtCore.QSize(55, 35))
        self.btn_normalize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_normalize.setStyleSheet("")
        self.btn_normalize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/src/icons/notfullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_normalize.setIcon(icon2)
        self.btn_normalize.setIconSize(QtCore.QSize(29, 29))
        self.btn_normalize.setObjectName("btn_normalize")
        self.horizontalLayout.addWidget(self.btn_normalize)
        self.btn_maximize = QtWidgets.QPushButton(self.fr_top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_maximize.sizePolicy().hasHeightForWidth())
        self.btn_maximize.setSizePolicy(sizePolicy)
        self.btn_maximize.setMinimumSize(QtCore.QSize(55, 35))
        self.btn_maximize.setMaximumSize(QtCore.QSize(55, 35))
        self.btn_maximize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_maximize.setStyleSheet("")
        self.btn_maximize.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/src/icons/fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximize.setIcon(icon3)
        self.btn_maximize.setIconSize(QtCore.QSize(29, 29))
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout.addWidget(self.btn_maximize)
        self.btn_close = QtWidgets.QPushButton(self.fr_top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(55, 35))
        self.btn_close.setMaximumSize(QtCore.QSize(55, 35))
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgba(170, 0, 0,0.8);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(150, 0, 0,0.7);\n"
"}")
        self.btn_close.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/src/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon4)
        self.btn_close.setIconSize(QtCore.QSize(29, 29))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.verticalLayout_5.addWidget(self.fr_top_bar)
        self.fr_content = QtWidgets.QFrame(self.centralwidget)
        self.fr_content.setMinimumSize(QtCore.QSize(0, 0))
        self.fr_content.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fr_content.setStyleSheet("")
        self.fr_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_content.setObjectName("fr_content")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.fr_content)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fr_menu = QtWidgets.QFrame(self.fr_content)
        self.fr_menu.setMinimumSize(QtCore.QSize(200, 0))
        self.fr_menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.fr_menu.setStyleSheet("QPushButton {\n"
"    background-color: rgb(30, 30, 30);\n"
"    border: 0px;\n"
"    color: rgba(255, 255, 255, 0.6);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgba(255, 255, 255, 0.9);\n"
"    background-color: rgba(255, 255, 255, 0.1)\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(155, 155, 155, 0.2)\n"
"}\n"
"\n"
"QFrame{\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgba(255, 255, 255, 0.8);\n"
"}")
        self.fr_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_menu.setObjectName("fr_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fr_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_5 = QtWidgets.QFrame(self.fr_menu)
        self.line_5.setMinimumSize(QtCore.QSize(200, 1))
        self.line_5.setMaximumSize(QtCore.QSize(1, 1))
        self.line_5.setStyleSheet("background-color: rgba(0, 0, 0, 0.1);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.fr_connection = QtWidgets.QFrame(self.fr_menu)
        self.fr_connection.setMinimumSize(QtCore.QSize(200, 80))
        self.fr_connection.setMaximumSize(QtCore.QSize(200, 80))
        self.fr_connection.setStyleSheet("QComboBox{\n"
"    padding-left: 2px;\n"
"    border: 1px solid;\n"
"    border-color: rgb(30, 30, 30);\n"
"    color: rgba(255, 255, 255, 0.6);\n"
"    background-color: rgb(20, 20, 20);\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: rgb(22, 22, 22);\n"
"}\n"
"\n"
"QComboBox:drop-down{\n"
"    border: 0px solid;\n"
"    color: rgba(255, 255, 255, 0.6);\n"
"}\n"
"\n"
"QComboBox QAbstractItem{\n"
"    selection-background-color:   rgb(47, 175, 178);\n"
"    border: none;\n"
"}\n"
"\n"
"QListView{\n"
"    color: rgba(255, 255, 255, 0.6);\n"
"    border: 0px;\n"
"}\n"
"")
        self.fr_connection.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_connection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_connection.setObjectName("fr_connection")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fr_connection)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fr_ports = QtWidgets.QFrame(self.fr_connection)
        self.fr_ports.setMinimumSize(QtCore.QSize(200, 40))
        self.fr_ports.setMaximumSize(QtCore.QSize(200, 40))
        self.fr_ports.setStyleSheet("")
        self.fr_ports.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_ports.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_ports.setObjectName("fr_ports")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fr_ports)
        self.horizontalLayout_4.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_Ports = QtWidgets.QLabel(self.fr_ports)
        self.lb_Ports.setMinimumSize(QtCore.QSize(0, 30))
        self.lb_Ports.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lb_Ports.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_Ports.setStyleSheet("")
        self.lb_Ports.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_Ports.setObjectName("lb_Ports")
        self.horizontalLayout_4.addWidget(self.lb_Ports)
        self.cb_ports = QtWidgets.QComboBox(self.fr_ports)
        self.cb_ports.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cb_ports.setStyleSheet("border-radius: 1px;")
        self.cb_ports.setPlaceholderText("")
        self.cb_ports.setObjectName("cb_ports")
        self.horizontalLayout_4.addWidget(self.cb_ports)
        self.verticalLayout_2.addWidget(self.fr_ports)
        self.fr_bauds = QtWidgets.QFrame(self.fr_connection)
        self.fr_bauds.setMinimumSize(QtCore.QSize(200, 40))
        self.fr_bauds.setMaximumSize(QtCore.QSize(200, 40))
        self.fr_bauds.setStyleSheet("")
        self.fr_bauds.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_bauds.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_bauds.setObjectName("fr_bauds")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fr_bauds)
        self.horizontalLayout_3.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_Baudrate = QtWidgets.QLabel(self.fr_bauds)
        self.lb_Baudrate.setMinimumSize(QtCore.QSize(0, 30))
        self.lb_Baudrate.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lb_Baudrate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_Baudrate.setObjectName("lb_Baudrate")
        self.horizontalLayout_3.addWidget(self.lb_Baudrate)
        self.cb_bauds = QtWidgets.QComboBox(self.fr_bauds)
        self.cb_bauds.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cb_bauds.setStyleSheet("border-radius: 1px;")
        self.cb_bauds.setCurrentText("")
        self.cb_bauds.setPlaceholderText("")
        self.cb_bauds.setObjectName("cb_bauds")
        self.horizontalLayout_3.addWidget(self.cb_bauds)
        self.verticalLayout_2.addWidget(self.fr_bauds)
        self.verticalLayout_3.addWidget(self.fr_connection)
        self.line_6 = QtWidgets.QFrame(self.fr_menu)
        self.line_6.setMinimumSize(QtCore.QSize(200, 1))
        self.line_6.setMaximumSize(QtCore.QSize(1, 1))
        self.line_6.setStyleSheet("background-color: rgba(0, 0, 0, 0.1);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_3.addWidget(self.line_6)
        self.fr_connection_btn = QtWidgets.QFrame(self.fr_menu)
        self.fr_connection_btn.setMinimumSize(QtCore.QSize(200, 30))
        self.fr_connection_btn.setMaximumSize(QtCore.QSize(200, 30))
        self.fr_connection_btn.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"color: rgba(255, 255, 255, 0.5);\n"
"background-color: rgb(39, 39, 39);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(155, 155, 155, 0.1)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(155, 155, 155, 0.2)\n"
"}\n"
"")
        self.fr_connection_btn.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_connection_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_connection_btn.setObjectName("fr_connection_btn")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fr_connection_btn)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_connect_serial = QtWidgets.QPushButton(self.fr_connection_btn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_connect_serial.sizePolicy().hasHeightForWidth())
        self.btn_connect_serial.setSizePolicy(sizePolicy)
        self.btn_connect_serial.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_connect_serial.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_connect_serial.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_connect_serial.setStyleSheet("QPushButton{\n"
"color: rgb(168, 0, 42);\n"
"border: 0.5px solid;\n"
"border-color: rgb(168, 0, 42);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"color:  rgb(140, 184, 84);\n"
"border: 0.5px solid;\n"
"border-color:  rgb(140, 184, 84);\n"
"}\n"
"\n"
"\n"
"")
        self.btn_connect_serial.setCheckable(True)
        self.btn_connect_serial.setObjectName("btn_connect_serial")
        self.horizontalLayout_2.addWidget(self.btn_connect_serial)
        self.btn_update_ports = QtWidgets.QPushButton(self.fr_connection_btn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_update_ports.sizePolicy().hasHeightForWidth())
        self.btn_update_ports.setSizePolicy(sizePolicy)
        self.btn_update_ports.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_update_ports.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_update_ports.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_update_ports.setStyleSheet("")
        self.btn_update_ports.setObjectName("btn_update_ports")
        self.horizontalLayout_2.addWidget(self.btn_update_ports)
        self.verticalLayout_3.addWidget(self.fr_connection_btn)
        self.line_7 = QtWidgets.QFrame(self.fr_menu)
        self.line_7.setMinimumSize(QtCore.QSize(200, 1))
        self.line_7.setMaximumSize(QtCore.QSize(1, 1))
        self.line_7.setStyleSheet("background-color: rgba(0, 0, 0, 0.1);")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_3.addWidget(self.line_7)
        self.fr_util_btn = QtWidgets.QFrame(self.fr_menu)
        self.fr_util_btn.setMinimumSize(QtCore.QSize(200, 30))
        self.fr_util_btn.setMaximumSize(QtCore.QSize(200, 30))
        self.fr_util_btn.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"color: rgba(255, 255, 255, 0.5);\n"
"background-color: rgb(39, 39, 39);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(155, 155, 155, 0.1)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(155, 155, 155, 0.2)\n"
"}\n"
"")
        self.fr_util_btn.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_util_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_util_btn.setObjectName("fr_util_btn")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.fr_util_btn)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_togle_log = QtWidgets.QPushButton(self.fr_util_btn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_togle_log.sizePolicy().hasHeightForWidth())
        self.btn_togle_log.setSizePolicy(sizePolicy)
        self.btn_togle_log.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_togle_log.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_togle_log.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_togle_log.setStyleSheet("\n"
"QPushButton:checked{\n"
"color: rgb(140, 184, 84);\n"
"border: 0.5px solid;\n"
"border-color: rgb(140, 184, 84);\n"
"}\n"
"")
        self.btn_togle_log.setCheckable(True)
        self.btn_togle_log.setObjectName("btn_togle_log")
        self.horizontalLayout_6.addWidget(self.btn_togle_log)
        self.btn_clear = QtWidgets.QPushButton(self.fr_util_btn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear.sizePolicy().hasHeightForWidth())
        self.btn_clear.setSizePolicy(sizePolicy)
        self.btn_clear.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_clear.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clear.setStyleSheet("")
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout_6.addWidget(self.btn_clear)
        self.verticalLayout_3.addWidget(self.fr_util_btn)
        self.line_9 = QtWidgets.QFrame(self.fr_menu)
        self.line_9.setMinimumSize(QtCore.QSize(200, 1))
        self.line_9.setMaximumSize(QtCore.QSize(1, 1))
        self.line_9.setStyleSheet("background-color: rgba(0, 0, 0, 0.1);")
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_3.addWidget(self.line_9)
        self.btn_menu_1 = QtWidgets.QPushButton(self.fr_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_menu_1.sizePolicy().hasHeightForWidth())
        self.btn_menu_1.setSizePolicy(sizePolicy)
        self.btn_menu_1.setMinimumSize(QtCore.QSize(200, 40))
        self.btn_menu_1.setMaximumSize(QtCore.QSize(200, 40))
        self.btn_menu_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_menu_1.setStyleSheet("")
        self.btn_menu_1.setCheckable(False)
        self.btn_menu_1.setChecked(False)
        self.btn_menu_1.setObjectName("btn_menu_1")
        self.verticalLayout_3.addWidget(self.btn_menu_1)
        self.line_12 = QtWidgets.QFrame(self.fr_menu)
        self.line_12.setMinimumSize(QtCore.QSize(200, 1))
        self.line_12.setMaximumSize(QtCore.QSize(1, 1))
        self.line_12.setStyleSheet("background-color: rgba(0, 0, 0, 0.1);")
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_3.addWidget(self.line_12)
        self.btn_menu_2 = QtWidgets.QPushButton(self.fr_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_menu_2.sizePolicy().hasHeightForWidth())
        self.btn_menu_2.setSizePolicy(sizePolicy)
        self.btn_menu_2.setMinimumSize(QtCore.QSize(200, 40))
        self.btn_menu_2.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Arame Mono")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_menu_2.setFont(font)
        self.btn_menu_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_menu_2.setCheckable(False)
        self.btn_menu_2.setObjectName("btn_menu_2")
        self.verticalLayout_3.addWidget(self.btn_menu_2)
        self.line_8 = QtWidgets.QFrame(self.fr_menu)
        self.line_8.setMinimumSize(QtCore.QSize(200, 1))
        self.line_8.setMaximumSize(QtCore.QSize(1, 1))
        self.line_8.setStyleSheet("background-color: rgba(0, 0, 0, 0.1);")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_3.addWidget(self.line_8)
        spacerItem1 = QtWidgets.QSpacerItem(20, 366, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.line_11 = QtWidgets.QFrame(self.fr_menu)
        self.line_11.setMinimumSize(QtCore.QSize(200, 1))
        self.line_11.setMaximumSize(QtCore.QSize(200, 1))
        self.line_11.setStyleSheet("background-color: rgba(0, 0, 0, 0.1);")
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_3.addWidget(self.line_11)
        self.btn_menu_config = QtWidgets.QPushButton(self.fr_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_menu_config.sizePolicy().hasHeightForWidth())
        self.btn_menu_config.setSizePolicy(sizePolicy)
        self.btn_menu_config.setMinimumSize(QtCore.QSize(200, 40))
        self.btn_menu_config.setMaximumSize(QtCore.QSize(200, 40))
        self.btn_menu_config.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_menu_config.setCheckable(False)
        self.btn_menu_config.setObjectName("btn_menu_config")
        self.verticalLayout_3.addWidget(self.btn_menu_config)
        self.horizontalLayout_5.addWidget(self.fr_menu)
        self.stackedWidget = QtWidgets.QStackedWidget(self.fr_content)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setStyleSheet("QTextBrowser{\n"
"background-color: rgba(20,21,22,255);\n"
"}\n"
"QScrollBar{\n"
"    border:none;\n"
"    background-color: rgb(32, 32, 32);\n"
"    width:14px;\n"
"    margin:15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle::vertical{\n"
"    background-color: rgb(50, 52, 54);\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle::vertical:hover{\n"
"    \n"
"    background-color: rgb(73, 75, 78);\n"
"}\n"
"\n"
"QScrollBar::sub-line{\n"
"    border: none;\n"
"    background-color: rgb(50, 52, 54);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    image: url(:/src/icons/arrow_up.png);\n"
"    border: none;\n"
"    background-color: rgb(50, 52, 54);\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(73, 75, 78);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(55, 55, 55);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    image: url(:/src/icons/arrow_down.png);\n"
"    border: none;\n"
"    background-color: rgb(50, 52, 54);\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(73, 75, 78);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(55, 55, 55);\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.page_1.setObjectName("page_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.terminal = QtWidgets.QTextBrowser(self.page_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminal.sizePolicy().hasHeightForWidth())
        self.terminal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arame Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.terminal.setFont(font)
        self.terminal.setStyleSheet("QTextBrowser{\n"
"    color:rgba(77, 235, 220, 0.8);\n"
"    border: 0px solid;\n"
"    font: 10pt \"Arame Mono\";\n"
"    text-align: left;\n"
"}\n"
"\n"
"\n"
"")
        self.terminal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.terminal.setFrameShadow(QtWidgets.QFrame.Plain)
        self.terminal.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.terminal.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.terminal.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.terminal.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.terminal.setDocumentTitle("")
        self.terminal.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.terminal.setMarkdown("")
        self.terminal.setOverwriteMode(False)
        self.terminal.setPlaceholderText("")
        self.terminal.setOpenLinks(False)
        self.terminal.setObjectName("terminal")
        self.verticalLayout_4.addWidget(self.terminal)
        self.fr_command_input = QtWidgets.QFrame(self.page_1)
        self.fr_command_input.setMinimumSize(QtCore.QSize(0, 30))
        self.fr_command_input.setMaximumSize(QtCore.QSize(16777215, 30))
        self.fr_command_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fr_command_input.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.fr_command_input.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_command_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_command_input.setObjectName("fr_command_input")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.fr_command_input)
        self.horizontalLayout_7.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.terminal_input = QtWidgets.QLineEdit(self.fr_command_input)
        self.terminal_input.setMinimumSize(QtCore.QSize(0, 30))
        self.terminal_input.setMaximumSize(QtCore.QSize(16777215, 30))
        self.terminal_input.setStyleSheet("font: 10pt \"Arame Mono\";\n"
"color: rgba(255, 255, 255, 0.8);\n"
"background-color: rgb(49, 49, 49);\n"
"border: 0px solid;")
        self.terminal_input.setObjectName("terminal_input")
        self.horizontalLayout_7.addWidget(self.terminal_input)
        self.line_10 = QtWidgets.QFrame(self.fr_command_input)
        self.line_10.setMinimumSize(QtCore.QSize(1, 30))
        self.line_10.setMaximumSize(QtCore.QSize(1, 30))
        self.line_10.setStyleSheet("background-color: rgba(0, 0, 0, 0.5);")
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_7.addWidget(self.line_10)
        self.btn_send = QtWidgets.QPushButton(self.fr_command_input)
        self.btn_send.setMinimumSize(QtCore.QSize(60, 30))
        self.btn_send.setMaximumSize(QtCore.QSize(60, 30))
        self.btn_send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_send.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"color: rgba(255, 255, 255, 0.5);\n"
"background-color: rgb(49, 49, 49);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(65,65, 65, 0.5);\n"
"}\n"
"")
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout_7.addWidget(self.btn_send)
        self.verticalLayout_4.addWidget(self.fr_command_input)
        self.stackedWidget.addWidget(self.page_1)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("color: rgba(255, 255, 255, 0.7);\n"
"background-color: rgba(20,21,22,255);\n"
"border: 0px solid;")
        self.page_3.setObjectName("page_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.fr_config = QtWidgets.QFrame(self.page_3)
        self.fr_config.setStyleSheet("Line{\n"
"    background-color:rgba(255,255,255,0.1);\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    border: 1px solid;\n"
"    border-color: rgb(220,220,220);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"    background-color: rgba(115, 175, 160, 0.9);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover{\n"
"    background-color: rgba(115, 175, 160, 0.9);\n"
"}\n"
"\n"
"QCheckBox::indicator:hover{\n"
"    background-color: rgba(240,240,240,0.1);\n"
"}\n"
"\n"
"QCheckBox:hover{\n"
"    color: rgb(250,250,250);\n"
"}\n"
"")
        self.fr_config.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_config.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_config.setObjectName("fr_config")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.fr_config)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fr_config_buttons = QtWidgets.QFrame(self.fr_config)
        self.fr_config_buttons.setStyleSheet("QPushButton {\n"
"    border: 1px solid;\n"
"    border-color: rgb(220,220,220);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(155, 155, 155, 0.1)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(155, 155, 155, 0.2)\n"
"}\n"
"")
        self.fr_config_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_config_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_config_buttons.setObjectName("fr_config_buttons")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.fr_config_buttons)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btn_refresh = QtWidgets.QPushButton(self.fr_config_buttons)
        self.btn_refresh.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_refresh.setMaximumSize(QtCore.QSize(60, 25))
        self.btn_refresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_refresh.setStyleSheet("border-radius: 2px;")
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout_12.addWidget(self.btn_refresh)
        self.btn_opn_logs = QtWidgets.QPushButton(self.fr_config_buttons)
        self.btn_opn_logs.setMinimumSize(QtCore.QSize(100, 25))
        self.btn_opn_logs.setMaximumSize(QtCore.QSize(60, 25))
        self.btn_opn_logs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_opn_logs.setStyleSheet("border-radius: 2px;")
        self.btn_opn_logs.setObjectName("btn_opn_logs")
        self.horizontalLayout_12.addWidget(self.btn_opn_logs)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.verticalLayout_6.addWidget(self.fr_config_buttons)
        self.fr_config_default_bauds = QtWidgets.QFrame(self.fr_config)
        self.fr_config_default_bauds.setStyleSheet("QComboBox{\n"
"    border: 1px solid;\n"
"    border-left: 0px;\n"
"    border-color: rgb(220,220,220);\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: rgb(22, 22, 22);\n"
"}\n"
"\n"
"QComboBox QAbstractItem{\n"
"    selection-background-color:   rgb(47, 175, 178);\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox:QAbstractItem:hover{\n"
"    color:rgba(52, 175, 160, 0.9);\n"
"}\n"
"\n"
"\n"
"QListView{\n"
"    color: rgba(255, 255, 255, 0.6);\n"
"    border: 0px;\n"
"}\n"
"")
        self.fr_config_default_bauds.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_config_default_bauds.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_config_default_bauds.setObjectName("fr_config_default_bauds")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.fr_config_default_bauds)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.config_default_bauds_label = QtWidgets.QLabel(self.fr_config_default_bauds)
        self.config_default_bauds_label.setMinimumSize(QtCore.QSize(0, 19))
        self.config_default_bauds_label.setMaximumSize(QtCore.QSize(16777215, 19))
        self.config_default_bauds_label.setStyleSheet("border: 1px solid;\n"
"border-right: 0px;\n"
"border-color: rgb(220,220,220);")
        self.config_default_bauds_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.config_default_bauds_label.setObjectName("config_default_bauds_label")
        self.horizontalLayout_8.addWidget(self.config_default_bauds_label)
        self.config_default_bauds = QtWidgets.QComboBox(self.fr_config_default_bauds)
        self.config_default_bauds.setMinimumSize(QtCore.QSize(80, 0))
        self.config_default_bauds.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.config_default_bauds.setStyleSheet("")
        self.config_default_bauds.setCurrentText("")
        self.config_default_bauds.setPlaceholderText("")
        self.config_default_bauds.setObjectName("config_default_bauds")
        self.horizontalLayout_8.addWidget(self.config_default_bauds)
        spacerItem3 = QtWidgets.QSpacerItem(745, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_6.addWidget(self.fr_config_default_bauds)
        self.btn_start_max = QtWidgets.QCheckBox(self.fr_config)
        self.btn_start_max.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_start_max.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_start_max.setStyleSheet("border-radius: 25px;")
        self.btn_start_max.setObjectName("btn_start_max")
        self.verticalLayout_6.addWidget(self.btn_start_max)
        self.btn_auto_update = QtWidgets.QCheckBox(self.fr_config)
        self.btn_auto_update.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_auto_update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_auto_update.setStyleSheet("")
        self.btn_auto_update.setObjectName("btn_auto_update")
        self.verticalLayout_6.addWidget(self.btn_auto_update)
        self.btn_set_full_screen = QtWidgets.QCheckBox(self.fr_config)
        self.btn_set_full_screen.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_set_full_screen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_set_full_screen.setStyleSheet("")
        self.btn_set_full_screen.setObjectName("btn_set_full_screen")
        self.verticalLayout_6.addWidget(self.btn_set_full_screen)
        spacerItem4 = QtWidgets.QSpacerItem(20, 615, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.verticalLayout_7.addWidget(self.fr_config)
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("QWidget{\n"
"    color:rgba(77, 235, 220, 0.8);\n"
"    background-color: rgba(20,21,22,255);\n"
"    border: 0px solid;\n"
"}\n"
"QGroupBox{\n"
"border: 1px solid rgba(255, 255, 255, 0.2);\n"
"color: rgba(255, 255, 255, 0.5);\n"
"}\n"
"")
        self.page_2.setObjectName("page_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fr_flight = QtWidgets.QFrame(self.page_2)
        self.fr_flight.setStyleSheet("font: 250 9pt \"Arame\";")
        self.fr_flight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_flight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_flight.setObjectName("fr_flight")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.fr_flight)
        self.verticalLayout_8.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_8.setSpacing(3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.TelemetryGroup = QtWidgets.QGroupBox(self.fr_flight)
        self.TelemetryGroup.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arame Mono")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.TelemetryGroup.setFont(font)
        self.TelemetryGroup.setStyleSheet("font: 9pt \"Arame Mono\";")
        self.TelemetryGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.TelemetryGroup.setFlat(False)
        self.TelemetryGroup.setCheckable(False)
        self.TelemetryGroup.setChecked(False)
        self.TelemetryGroup.setObjectName("TelemetryGroup")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.TelemetryGroup)
        self.verticalLayout_9.setContentsMargins(0, 5, 2, 2)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.telemetry_graphs = QtWidgets.QVBoxLayout()
        self.telemetry_graphs.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.telemetry_graphs.setContentsMargins(0, 9, 0, 0)
        self.telemetry_graphs.setSpacing(0)
        self.telemetry_graphs.setObjectName("telemetry_graphs")
        self.verticalLayout_9.addLayout(self.telemetry_graphs)
        self.verticalLayout_8.addWidget(self.TelemetryGroup)
        self.verticalLayout.addWidget(self.fr_flight)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_5.addWidget(self.stackedWidget)
        self.stackedWidget.raise_()
        self.fr_menu.raise_()
        self.verticalLayout_5.addWidget(self.fr_content)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setMinimumSize(QtCore.QSize(0, 13))
        self.statusBar.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setFamily("Arame Mono")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        self.statusBar.setFont(font)
        self.statusBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.time_label.setText(_translate("MainWindow", "N/A"))
        self.lb_countdown.setText(_translate("MainWindow", "N/A"))
        self.lb_telemetry_info_1.setText(_translate("MainWindow", "N/A"))
        self.lb_Ports.setText(_translate("MainWindow", "PORT:"))
        self.lb_Baudrate.setText(_translate("MainWindow", "BAUDRATE:"))
        self.btn_connect_serial.setText(_translate("MainWindow", "disconnected"))
        self.btn_update_ports.setText(_translate("MainWindow", "Update"))
        self.btn_togle_log.setText(_translate("MainWindow", "RECORD"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.btn_menu_1.setText(_translate("MainWindow", "TERMINAL"))
        self.btn_menu_2.setText(_translate("MainWindow", "FLIGHT"))
        self.btn_menu_config.setText(_translate("MainWindow", "CONFIG"))
        self.terminal.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Arame Mono\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.terminal_input.setPlaceholderText(_translate("MainWindow", ">_"))
        self.btn_send.setText(_translate("MainWindow", ">>"))
        self.btn_refresh.setText(_translate("MainWindow", "RELOAD"))
        self.btn_opn_logs.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_opn_logs.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_opn_logs.setText(_translate("MainWindow", "open saves "))
        self.config_default_bauds_label.setText(_translate("MainWindow", "Default Bauds:"))
        self.btn_start_max.setText(_translate("MainWindow", "start maximized"))
        self.btn_auto_update.setText(_translate("MainWindow", "UPDATE PORTS ON START"))
        self.btn_set_full_screen.setText(_translate("MainWindow", "FULL SCREEN"))
        self.TelemetryGroup.setTitle(_translate("MainWindow", "FLY TELEMETRY"))
import edvs.ui.resources.src_rc
